# Generated by Django 4.1.1 on 2022-11-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spkapp', '0004_alter_order_model_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='projectname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spkapp.projects'),
        ),
    ]
