# Generated by Django 4.1.1 on 2022-11-21 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spkapp', '0005_alter_order_model_projectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order_model',
            name='orderno',
            field=models.CharField(default='SPK-00001', max_length=10),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Checked', 'Checked'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='order_model',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spkapp.vendor'),
        ),
    ]
